### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by afonso-a** [unknownsrc/tokens#13]
In FAQ you say: "What did you do to my token?
I have collected information about it and added it to my database and then invalidated it. Nothing more, nothing less"
I would like to know what type of information you collected.

**Comment by unknownsrc** [comment]
https://discord.com/developers/docs/resources/application

I saved the data listed in that object

**Comment by skidmaster69420** [comment]
Hello there,

thank you for writing us, I can see that you have already got a legitimate answer, so let me also reply. I want to tell you about my Mom and Uncle who have recently begun chasing me. My mother has a gun and my Uncle wants me to suck his ass. I feel very uncomfortable with that sort of energy, but I suppose that's just life for you. I mean all I did was work for a company that doesn't pay me and now they want to take me out for doing that. I mean in a sense, I am doing charity work, but no... they want me dead! This has me truly upset, because usually people like me should be getting treated like heroes, but that's not the case! I get treated like trash that's left behind by fast food diners, which are disgusting btw. Anyhow, getting off topic. Well turns out I worried for nothing because Boss ran over my Uncle and Mother with his Buggati. After he did that, he went up to their corpses and asked them "WHAT COLOR IS YOUR BUGATTI". Well, I only know this because he sent me the video of him running them over, he of course then proceeded to t-bag on their corpses. I guess I have nothing to worry about it.

Thank you for your question

yours, 
Unpaid Intern
Skidmaster69420LLC
