### ISSUE TITLE
I See you got my bot token there, discord notified me. why did u store it there? 

### ISSUE THREAD

**Issue by TragicLOL** [unknownsrc/tokens#18]
fuck off unknowsrc

**Comment by IMarkoMC** [comment]
Ok skid cry harder

**Comment by User9684** [comment]
cope

**Comment by TragicLOL** [comment]
maybe you cry motherfucker

**Comment by IMarkoMC** [comment]
> maybe you cry motherfucker

U mad? LMFAO 

Go learn how to properly store a bot token... 
You should be thankful that we found your token and didn't use it to nuke some server or nuked your own server idiot

**Comment by CreatorvsIShere** [comment]
IMakroMC 132.69.86.675

**Comment by unknownsrc** [comment]
dumbass above me

**Comment by CreatorvsIShere** [comment]
unkownsrc i know how you find our tokens
and you are a shit

**Comment by CreatorvsIShere** [comment]
LMAO my friend can hack you 
he has hacked so many people that he have found phone numbers by beaming

**Comment by CreatorvsIShere** [comment]
TragicLOL me and my friend are better than you bullshit

**Comment by IMarkoMC** [comment]
Cry harder skid. I'm having the laugh of my life with your nonsense

**Comment by User9684** [comment]
> LMAO my friend can hack you he has hacked so many people that he have found phone numbers by beaming

Do it then, hack me.

**Comment by CreatorvsIShere** [comment]
not you dummy IMakroMC and unkownrsc

**Comment by CreatorvsIShere** [comment]
but atleast im not shit

**Comment by CreatorvsIShere** [comment]
[shutv3s_personal_data.txt](https://github.com/unknownsrc/tokens/files/9371773/shutv3s_personal_data.txt)
open this and you will see what we have done unkownsrc and IMakroMC bc you are dumbasses that dont believe anything

**Comment by IMarkoMC** [comment]
Yeah I'll open a file from a idiot claiming to be a hacker. 

Cry harder skid

**Comment by unknownsrc** [comment]
> [shutv3s_personal_data.txt](https://github.com/unknownsrc/tokens/files/9371773/shutv3s_personal_data.txt) open this and you will see what we have done unkownsrc and IMakroMC bc you are dumbasses that dont believe anything

clownery at its finest

**Comment by Whanos** [comment]
you're 12
[creator_personal_data.txt](https://github.com/unknownsrc/tokens/files/9376376/creator_personal_data.txt)
@CreatorvsIShere

**Comment by skidmaster69420** [comment]
EMERGENCY COMMENT.

I clicked on the thing, and it showed me how you look like. And I am not kidding, I had to go to the Emergency room for emergency surgery. It took 24 hours in order to get me back to somewhat operational status. The doctors asked me, how I managed to get that badly injured. I then subsequently said "I had a look at this person's face", sadly they then asked to take a look, so I showed them your face. ALL THE DOCTORS DIED ON THE SPOT. You have killed 5 people with how you look, which has caused a small crisis. You should really REALLY consider taking a shower, it has been months and rats have started to call your clothes home with how stinky they are. I would seriously advise you to... just report yourself to a health department for immediate sanitation, you would save MILLIONS. 

Thank you, but please NEVER send any files again. Because they may still contain a picture of yours.
Don't cause people the pain I had to endure.

**Comment by unknownsrc** [comment]
I agree
