### ISSUE TITLE
Why are you doing this?

### ISSUE THREAD

**Issue by EnwoNyaw** [unknownsrc/tokens#21]
Why are you doing this?
it's just for fun?

**Comment by User9684** [comment]
cus why not

**Comment by Scalamobile** [comment]
this is not fun

**Comment by unknownsrc** [comment]
it is

**Comment by skidmaster69420** [comment]
Thank you for your inquiry.

We are doing this because we want to see you cry, your tears are the fuel that we run on. And since the fuel crisis continues, you better continue crying so that we can power our devices. Keep those tears coming, and we'll relinquish every single moment of it. Because you'll be the hero to safe America from its crisis with the amount of tears that you'll cry, which shall surpass any fuel reserve on earth. The world is counting upon you to continue being butt hurt. Thank you.
