### ISSUE TITLE
LMAO KIDS

### ISSUE THREAD

**Issue by CreatorvsIShere** [unknownsrc/tokens#22]
you are kids and you want to nuke/sell our servers noobs i wont fall for the repl fork thinl again you bullshits

**Comment by CreatorvsIShere** [comment]
GO CRY STAY MAD ABT IT SKIDS NOOBS NO DAD? GO CRY MEOWBAHH IS BETTER THAN YOU NOOBS

**Comment by unknownsrc** [comment]
> you are kids and you want to nuke/sell our servers noobs i wont fall for the repl fork thinl again you bullshits

what? i am literally invalidating ur tokens so no one else does that lmfao

**Comment by unknownsrc** [comment]
> GO CRY STAY MAD ABT IT SKIDS NOOBS NO DAD? GO CRY MEOWBAHH IS BETTER THAN YOU NOOBS

stay mad

**Comment by IMarkoMC** [comment]
Ok skid cry harder

**Comment by CreatorvsIShere** [comment]
i have a milk and dad and you dont and atleast im not shit

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by Whanos** [comment]
@CreatorvsIShere your mum used you as a fuckin pingpong ball

**Comment by skidmaster69420** [comment]
Hello there,

Thank you so much for calling us kids. Sadly we have to report... that.. you have fully surpassed us. You have absolutely defeated us. You have dethroned us. Our honor is wounded, our people hurt. Because...


You fully and utterly managed to show us, how much of a kid you truly are. Outshining all of us. You have the ability to return to your embryo state. For your intelligence truly is comparable to that of a child that hasn't been born yet. If we were to compare your intelligence to that of a fly, it would be an insult to the fly and cause a catastrophe. Hence we have decided... to fully respect your authority of the dumbest being of earth. Sadly... you have also lost the ability to refer to yourself as a human due to the intelligence level that you have showed us. Hence we are referring to you here as a "being". We will write you a separate message once we manage to figure out, what you should be qualified as.

**Comment by RealmKebab** [comment]
^

i dont know why NOBODY reads the markdown of "readme" before posting, like they just ignore it completely

**Comment by skidmaster69420** [comment]
> ^
> 
> i dont know why NOBODY reads the markdown of "readme" before posting, like they just ignore it completely

We at SKIDMASTER42069 LLC, have successful trained hyperintelligent flies to be able to read on a 12th grade reading level (they really loved ["A MILLION Random Digits WITH 100,000 Normal Deviates"](https://www.rand.org/pubs/monograph_reports/MR1418.html)) for the SOLE purpose of proving how FLIES are better at reading then the author of this issue. Unfortunately for me, even the flies don't understand how the fuck to play Solitaire. Instead, we have trained the flies to make sure all Discord tokens brought home by our hyperintelligent token vultures are Kosher and don't contain malaria and/or lupus.

Although 1% of all flies have died in testing when asked to read this issue, no wonder nobody reads the readme before posting anymore. They died.

All the bestn't,

Unpaid Intern
SKIDMASTER42069 LLC
