### ISSUE TITLE
Reset my token lol it works fine

### ISSUE THREAD

**Issue by idkwhattoputherexd** [unknownsrc/tokens#3]
I AM THE STORM THAT IS APPROACHING
PROVOKING BLACK CLOUDS IN ISOLATION
I AM RECLAIMER OF MY NAME
BORN IN FLAMES, I HAVE BEEN BLESSED
MY FAMILY CREST IS A DEMON OF DEATH!

**Comment by RTgamerr** [comment]
Hello my good sir, are you high/drunk by any chance?

**Comment by BlackWolfWoof** [comment]
Lmao this issue is comedy gold

**Comment by skidmaster69420** [comment]
How dare you quote Metal Gear solid's song without including a picture of Snake's massive booty? 
Also, you should have asked Kojima for permission before even posting this, so you should do that right now. Otherwise I'll go to twitter and have you cancelled within 20 minutes. With the hashtag #ThisBootyWasTooBigForidkwhattoputherexd. Have a awful day, I hope you break both knee pads.
