### ISSUE TITLE
F*** You

### ISSUE THREAD

**Issue by Eithan123** [unknownsrc/tokens#9]

**Comment by unknownsrc** [comment]
love u too

**Comment by unknownsrc** [comment]
<3

**Comment by skidmaster69420** [comment]
Fuck you, Eithan123!
If you're dumb enough to post your token online this weekend
You're a big enough schmuck to come to unknownsrc's tokens!
Bad tokens! Bots that break down! Thieves!
If you think you're going to find a bargain at unknownsrc's
You can kiss my ass!
It's our belief that you're such a stupid motherfucker
You'll fall for this bullshit guaranteed!
If you find a better token
Shove it up your ugly ass!
You heard us right!
Shove it up your ugly ass!
Bring your token!
Bring your saltyness!
Bring your bot!
We'll fuck her! That's right!
We'll fuck your bot!
Because at unknownsrc's
You're fucked six ways from Sunday!
Take a hike to unknownsrc's
Home of Challenge Pissing! That's right!
Challenge Pissing!
How does it work?
If you can piss six feet in the air straight up
And not get wet
You get no snarky issue reply!
Don't wait! Don't delay! Don't fuck with us!
Or we'll rip your nuts off!
Only at unknownsrc's!
The only reposityory that tells you to fuck off!
Hurry up, asshole!
This event ends the minute after you stop posting your shit online
And it better not be invalid or you're a dead motherfucker!
Go to hell- unknownsrc's!
Github's filthiest
And exclusive home of the meanest sons-of-bitches
On the internet, guaranteed!
